version: "3.8"
services:
  backend:
    image: django-image:latest
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - mynetwork
    environment:
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=nexgen_db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=mysql
      - DB_PORT=3306
    restart: always

  mysql:
    image: mysql:latest
    networks:
      - mynetwork
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nexgen_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    restart: always

networks:
  mynetwork:
    name: django-network
    driver: bridge
